### ISSUE TITLE
'error: Name does not resolve' when deploying cluster-iperf/k8s/iperf-client-job.yaml on Kubernetes

### ISSUE THREAD

**Issue by MariaRogulenko** [Markbnj/cluster-iperf#1]
I modified yaml files a bit. 
Here is a server yaml file:

```
# Example deployment for an iperf service.
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: iperf-server
  labels:
    app: iperf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      name: iperf-server
      labels:
        app: iperf-server
    spec:
      containers:
      - name: iperf-server
        image: markbnj/cluster-iperf:0.0.1
        env:
        - name: ROLE
          value: server
        ports:
        - containerPort: 5001
---
# Example service front-end for an iperf service
apiVersion: v1
kind: Service
metadata:
  name: iperf-server
  labels:
    app: iperf-server
spec:
  selector:
    app: iperf-server
  ports:
  - port: 5001
    targetPort: 5001a
```

Here is a client yaml file:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: "iperf-client-job"
  labels:
    name: iperf-client-job
spec:
  template:
    metadata:
      labels:
        name: iperf-client-job
    spec:
      containers:
      - name: "iperf-client-job"
        image: markbnj/cluster-iperf:0.0.1
        env:
        - name: ROLE
          value: client
        - name: SERVER_ADDR
          value: iperf-server
        - name: RSYSLOG
          value: "false"
        - name: RSYSLOG_REMOTE
          value: "false"
      restartPolicy: OnFailure
```

When I deploy job, I'm getting the following error: 
`error: Name does not resolve`

However, I was able to run job successfully on my local machine.
Do you have any thoughts why it is happening?
